import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'Burner Safe Flow (v1.4.1)' }).click();
  await page1.goto('https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=ASKV5MgDYaK4lpbhQvsYovgcGZ59sWRVquP7tm626d7d6DDcfo-VUcHhAptQ9Q333qPnnH05yac5_A&osid=1&passive=1209600&service=mail&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-1542079346%3A1746571714620558');
  await page1.getByRole('textbox', { name: 'Email or phone' }).fill('shubham.agarwal8856@gmail.com');
  await page1.getByRole('textbox', { name: 'Email or phone' }).press('Enter');
  await page1.getByRole('link', { name: 'Try again' }).click();
  await page1.getByRole('link', { name: 'Sign into Gmail' }).click();
  await page1.getByRole('textbox', { name: 'Email or phone' }).fill('shubham.gupta2956@gmail.com');
  await page1.getByRole('textbox', { name: 'Email or phone' }).press('Enter');
  await page1.getByText('Try using a different browser').dblclick();
  await page1.getByText('This browser or app may not').click();
  await page.getByRole('textbox', { name: 'guardian@prove.email' }).click();
  await page.getByRole('textbox', { name: 'guardian@prove.email' }).fill('shubham.agarwal8856@gmail.com');
  await page.getByRole('button', { name: 'Create burner wallet' }).click();
  await expect(page.locator('div').filter({ hasText: 'Please check your email' }).nth(3)).toBeVisible();
  await expect(page.locator('#root div').filter({ hasText: 'Configure Recovery & Request' }).nth(4)).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Wallet Actions' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Trigger Recovery' })).toBeVisible();
  await page.getByRole('button', { name: 'Trigger Recovery' }).click();
  await expect(page.getByText('Guardian\'s Email')).toBeVisible();
  await page.getByRole('textbox', { name: '0xAB12...' }).click();
  await page.getByRole('textbox', { name: '0xAB12...' }).fill('0xE0387E390808cDbA9f2f86c555E406fC84f38aFC');
  await page.getByRole('button', { name: 'Trigger Recovery' }).click();
  await expect(page.getByText('Please check your email and')).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Trigger Recovery$/ }).nth(1)).toBeVisible();
  await expect(page.getByRole('heading', { name: 'You can recover your account' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Complete Recovery' })).toBeVisible();
});