export const STEPS = {
  STEP_SELECTION: 0,
  CONNECT_WALLETS: 1,
  SAFE_MODULE_RECOVERY: 2,
  REQUEST_GUARDIAN: 3,
  WALLET_ACTIONS: 4,
  CONFIGURE_GUARDIANS: 5,
  REQUESTED_RECOVERIES: 6,
  TRIGGER_ACCOUNT_RECOVERY: 7,
};

export const DEFAULT_EXPIRATION_TIME = 2n * 7n * 24n * 60n * 60n; // 2 weeks in seconds
export const DEFAULT_SIGNER_THRESHOLD = 1n; // Default threshold for signer weight
