export const STEPS = {
  STEP_SELECTION: 0,
  CONNECT_WALLETS: 1,
  SAFE_MODULE_RECOVERY: 2,
  REQUEST_GUARDIAN: 3,
  WALLET_ACTIONS: 4,
  CONFIGURE_GUARDIANS: 5,
  REQUESTED_RECOVERIES: 6,
  TRIGGER_ACCOUNT_RECOVERY: 7,
};
