name: Code Formatting Check

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
          cache: "yarn"
      - name: Install Prettier
        run: yarn add --dev prettier
      - name: Check code formatting
        run: yarn prettier --check .
